# Generated by Django 5.2.3 on 2025-06-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='ativos.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.PositiveIntegerField(default=5)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodicidade', to='ativos.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='TunelPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('estatico', 'Estático'), ('dinamico', 'Dinâmico'), ('assincrono', 'Assíncrono')], default='estatico', max_length=20)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tunel', to='ativos.ativo')),
            ],
        ),
    ]
